en:
  label: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: " "
  title: "NECCDL"
  params:
    description: "The Northeast Collegiate Cyber Defense League is an administrative body whose sole purpose is to facilitate the smooth running of NECCDC regardless of the yearly hosting institution"
    # main_cta:
    #   text: "Join"
    #   link: "/join/"
    footer_cta:
      text: "Sponsor"
      link: "/sponsor/"

  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1

    - identifier: "neccdc"
      name: "NECCDC"
      url: "/docs/neccdc"
      weight: 1
      post: "Documentation about the competition"
      parent: "about"

    - identifier: "volunteer"
      name: "Volunteer"
      url: "/volunteer/"
      weight: 2
      post: "Get involved with League"
      parent: "about"

    - identifier: "join"
      name: "Join"
      url: "/join/"
      weight: 2

    - identifier: "sponsor"
      name: "Sponsor"
      url: "/sponsor/"
      weight: 3

    - identifier: "history-2027"
      name: "NECCDC 2027"
      url: "/history/2027/"
      weight: 4

    - identifier: "history"
      name: "History"
      url: "/history/"
      weight: 5

    - identifier: "history-2026"
      name: "NECCDC 2026"
      url: "/history/2026/"
      weight: 993
      parent: "history"
    - identifier: "history-2025"
      name: "NECCDC 2025"
      url: "/history/2025/"
      weight: 993
      parent: "history"
    - identifier: "history-2024"
      name: "NECCDC 2024"
      url: "/history/2024/"
      weight: 994
      parent: "history"
    - identifier: "history-2023"
      name: "NECCDC 2023"
      url: "/history/2023/"
      weight: 995
      parent: "history"
    - identifier: "history-2022"
      name: "NECCDC 2022"
      url: "/history/2022/"
      weight: 996
      parent: "history"
    - identifier: "history-2021"
      name: "NECCDC 2021"
      url: "/history/2021/"
      weight: 997
      parent: "history"
    - identifier: "history-2020"
      name: "NECCDC 2020"
      url: "/history/2020/"
      weight: 998
      parent: "history"
    - identifier: "history-historic"
      name: "Historic"
      url: "/history/historic/"
      post: Results of competitions before written records
      weight: 999
      parent: "history"
