######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/images/dark-logo.png"
logo_on_black: "/images/light-logo.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/images/light-logo.png"]

github_edit: "Edit this page"

github:
  repo_url: "https://github.com/NECCDL/website/blob/main"
  show_edit_link: true

social_links:
  bluesky: "https://bsky.app/profile/neccdl.bsky.social"
  devstats: ""
  discord: "https://discord.gg/rJn6DxwFTC"
  facebook: ""
  flickr: ""
  github: "https://github.com/NECCDL/"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/neccdl"
  mastodon: "https://infosec.exchange/@neccdl"
  pinterest: ""
  rss: "https://github.com/NECCDL/website/commits/main/"
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  # youtube: "https://www.youtube.com/@northeastcollegiatecyberde2930"

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
